source "https://supermarket.chef.io"

metadata

cookbook "apt", path: "../vendor_deps/apt"
cookbook "apt-chef", path: "../vendor_deps/apt-chef"
cookbook "build-essential", path: "../vendor_deps/build-essential"
cookbook "chef-client", path: "../vendor_deps/chef-client"
cookbook "chef-ingredient", path: "../vendor_deps/chef-ingredient"
cookbook "chef-sugar", path: "../vendor_deps/chef-sugar"
cookbook "chef_handler", path: "../vendor_deps/chef_handler"
cookbook "compat_resource", path: "../vendor_deps/compat_resource"
cookbook "cron", path: "../vendor_deps/cron"
cookbook "firewall", path: "../vendor_deps/firewall"
cookbook "golang", path: "../vendor_deps/golang"
cookbook "libarchive", path: "../vendor_deps/libarchive"
cookbook "libartifact", path: "../vendor_deps/libartifact"
cookbook "logrotate", path: "../vendor_deps/logrotate"
cookbook "mingw", path: "../vendor_deps/mingw"
cookbook "nssm", path: "../vendor_deps/nssm"
cookbook "packagecloud", path: "../vendor_deps/packagecloud"
cookbook "poise", path: "../vendor_deps/poise"
cookbook "poise-service", path: "../vendor_deps/poise-service"
cookbook "push-jobs", path: "../vendor_deps/push-jobs"
cookbook "rhn", path: "../vendor_deps/rhn"
cookbook "rubyzip", path: "../vendor_deps/rubyzip"
cookbook "runit", path: "../vendor_deps/runit"
cookbook "selinux", path: "../vendor_deps/selinux"
cookbook "seven_zip", path: "../vendor_deps/seven_zip"
cookbook "ssl_certificate", path: "../vendor_deps/ssl_certificate"
cookbook "yum", path: "../vendor_deps/yum"
cookbook "yum-chef", path: "../vendor_deps/yum-chef"
cookbook "yum-epel", path: "../vendor_deps/yum-epel"
cookbook "windows", path: "../vendor_deps/windows"

cookbook "consul", path: "../vendor_forked/consul"
cookbook "hashicorp-vault", path: "../vendor_forked/hashicorp-vault"

cookbook "deps", path: "../deps"
cookbook "consul-cluster", path: "../consul-cluster"
